<div class="content__inner">
    <h2>搜索话题标签</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/search_hashtags"); ?>)</strong> API 访问话题标签搜索端点
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>query</td>
                <td>搜索关键词</td>
                <td>
                    例如: Covid19
                </td>
            </tr>
            <tr>
                <td>offset</td>
                <td>最后帖子偏移ID</td>
                <td>
                    仅在加载分页系统的帖子时需要。
                </td>
            </tr>
            <tr>
                <td>session_id (可选)</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>每次请求的帖子总数限制</td>
                <td>
                    推荐: 20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "找到结果",
        "data":[
            {
                "id": 6,
                "posts": 1,
                "tag": "covid",
                "time": "1605781894",
                "hashtag": "#covid",
                "url": "http://colibri.loc/search/posts?q=covid",
                "total": "1"
            }
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 204,
        "message": "未找到数据",
        "data": []
    }

    {
        "code": 400,
        "message": "搜索词无效或缺失",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>