<div class="modal popup-ticket-modal" tabindex="-1" role="dialog" data-backdrop="static" data-onclose="remove">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    银行转账收据
                </h5>
            </div>
            <div class="modal-body">
                <div class="user-info">
                    <div class="avatar">
                        <img src="<?php echo($cl['req_data']['avatar']); ?>" alt="Avatar">
                    </div>
                    <div class="uname">
                        <h5><?php echo($cl['req_data']['full_name']); ?></h5>
                        <a><?php echo($cl['req_data']['email']); ?></a>
                    </div>
                </div>

                <div class="text-message">
                    <h5>申请人留言：</h5>
                    <p>
                        <?php if (not_empty($cl['req_data']['text_message'])): ?>
                            <?php echo $cl['req_data']['text_message']; ?> - <b><a download="<?php echo($cl['req_data']['file_name']); ?>" href="<?php echo $cl['req_data']['receipt_img']; ?>">下载银行收据</a></b>
                        <?php else: ?>
                            该用户对此请求未留下评论
                        <?php endif; ?>
                    </p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>