<div class="content__inner">
    <h2>获取通知/提及</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/get_notifications"); ?>) API访问获取用户通知和提及的端点</strong> 
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>type</td>
                <td>通知类型（notifs/mentions）</td>
                <td>
                    例如: `notifs`
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>每次请求的记录总数限制</td>
                <td>
                    推荐: 20
                </td>
            </tr>
            <tr>
                <td>offset</td>
                <td>最后记录偏移ID</td>
                <td>
                    仅在加载分页系统的记录时需要。
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "获取成功",
        "data": [
            {
            "id": 36,
            "notifier_id": 73,
            "recipient_id": 7,
            "status": "0",
            "subject": "subscribe",
            "entry_id": 73,
            "json": "[]",
            "time": "19 hours ago",
            "username": "thomas_dugelman",
            "avatar": "http://colibri.loc/upload/default/avatar.png",
            "verified": "1",
            "name": "Thomas Dugelman",
            "url": "http://colibri.loc/@thomas_dugelman"
            },
            {...}
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 404,
        "message": "未找到数据",
        "data": []
    }

    {
        "code": 400,
        "message": "通知类型缺失或无效。请检查您的详细信息",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>