<div class="cp-app-container" data-app="account-verification">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                账户验证
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card" id="vue-cpanel-account-verification-app">
                <div class="header">
                    <h2>
                        账户验证请求 - ({{total_requests}})
                    </h2>
                </div>
                <div class="body">
                    <div class="regular-table">
                        <table class="table table-hover no-mb">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        用户名
                                    </th>
                                    <th>
                                        E-mail address
                                    </th>
                                    <th>
                                        最后上线时间
                                    </th>
                                    
                                    <th>
                                        状态
                                    </th>
                                    <th>
                                        请求时间
                                    </th>
                                    <th>
                                        操作
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-an="requests-list">
                                <?php if (not_empty($cl['requests'])): ?>
                                    <?php foreach ($cl['requests'] as $cl['li']): ?>
                                        <?php echo cl_template('cpanel/assets/account_verification/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="7">
                                            <div class="empty-table">
                                                <h4><?php echo('没有找到请求'); ?></h4>
                                                <p>
                                                    <?php echo('您的数据库中似乎还没有账户验证请求。所有账户验证请求都将显示在这里'); ?>
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                        <div class="table-pagination">
                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_prev_ctrl}" v-on:click="paginate('up')" href="javascript:void(0);" class="pagination-ctrls prev">
                                <?php echo cl_ficon("arrow_left"); ?>
                            </a>

                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_next_ctrl}" v-on:click="paginate('down')" href="javascript:void(0);" class="pagination-ctrls next">
                                <?php echo cl_ficon("arrow_right"); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/account_verification/scripts/app_master_script'); ?>