<div class="content__inner">
    <h2>通知令牌</h2>
    <p>
        使用此 <strong>(<?php echo cl_link("mobile_api/save_pnotif_token"); ?>)</strong> API访问通知令牌管理端点
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>token</td>
                <td>推送通知令牌</td>
                <td>
                    例如: c625cc16eb0096...
                </td>
            </tr>
            <tr>
                <td>type</td>
                <td>客户端设备类型</td>
                <td>
                    ios/android（默认为android）
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "通知令牌已保存",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data":[],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "message": "令牌值不正确",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>