<div class="content__inner">
    <h2>获取帖子点赞</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/fetch_likes"); ?>) API访问获取帖子点赞端点</strong> 
    </p>
    <p>
        <strong class="text-red tt-up">（获取帖子转发）目前脚本核心不支持此选项</strong> 
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID（可选）</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>post_id</td>
                <td>已点赞/未点赞的帖子整数ID</td>
                <td>
                    例如: 4567
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>每次请求的记录总数限制</td>
                <td>
                    推荐: 20
                </td>
            </tr>
            <tr>
                <td>offset</td>
                <td>最后帖子偏移ID</td>
                <td>
                    仅在加载分页系统的记录时需要。
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "点赞获取成功",
        "data": [
            {
                "offset_id": 3,
                "id": 7,
                "about": "",
                "followers": 3512,
                "posts": 4050,
                "avatar": "http://colibri.loc/upload/default/avatar.png",
                "last_active": "18 Nov, 20 04:11 PM",
                "username": "@dan_kassing",
                "fname": "Dan",
                "lname": "Kassing",
                "email": "ibragimov.ahmat.tl@gmail.com",
                "verified": "2",
                "name": "Dan Kassing",
                "url": "http://colibri.loc/@dan_kassing",
                "is_following": false,
                "is_user": false
            },
            {...},
            {...},
            {...}
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">
    {
        "code": 400,
        "message": "帖子ID缺失或无效",
        "data": []
    }

    {
        "code": 404,
        "message": "未找到数据",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>