<div class="content__inner">
	<h2>获取帖子数据</h2>
	<p>
	    请使用此 <strong>(<?php echo cl_link("mobile_api/thread_data"); ?>)</strong> API访问帖子线程数据端点
	</p>
	<h3>
		数据结构说明
	</h3>
	<br>

	<p>
		1. `post`变量包含线程的帖子数据（线程页面上的主帖子）
	</p>
	<p>
		2. `next`变量包含对线程的回复（此数组中的每个帖子数据也可以包含`replys`变量，其中包含对其的前几条回复）
	</p>
	<p>
		3. 名为`prev`的变量包含当前线程的父链（仅当存在父帖子时）
	</p>
	<p>
		4. 如果`can_reply`变量的值为false，则表示当前用户无法回复此帖子
	</p>
	<h4 class="table-title">GET参数</h4>
	<table class="table table-bordered">
	    <thead>
	    <tr>
	        <th width="15%">字段</th>
	        <th width="25%">值</th>
	        <th width="45%">说明</th>
	    </tr>
	    </thead>
	    <tbody>
	        <tr>
	            <td>session_id</td>
	            <td>​访问令牌ID</td>
	            <td>
	                例如: de25cc16eb00960f076...
	            </td>
	        </tr>
	        <tr>
	            <td>thread_id</td>
	            <td>帖子线程ID</td>
	            <td>
	                例如: 123456（任何帖子的ID，用于查看回复和所有详情）
	            </td>
	        </tr>
	    </tbody>
	</table>
	<h4 class="table-title">成功响应</h4>
	<div class="code-holder">
	    <div class="code-holder-inner">
	<pre><code class="json">{
		"code": 200,
		"data": {
			"can_reply": true,
			"post":{
				"id": 41,
				"user_id": 7,
				"text": "werwe",
				"type": "text",
				"replys_count": "1",
				"reposts_count": "0",
				"likes_count": "0",
				"status": "active",
				"thread_id": 40,
				"target": "pub_reply",
				"og_data": "",
				"time": "24 seconds ago",
				"advertising": false,
				"time_raw": "1605613164",
				"og_text": "werwe",
				"og_image": "statics/img/logo.png",
				"url": "http://colibri.loc/thread/41",
				"can_delete": true,
				"media":[],
				"is_owner": true,
				"has_liked": false,
				"has_saved": false,
				"has_reposted": false,
				"reply_to":{"id": 7, "url": "http://colibri.loc/@dan_kassing", "avatar": "http://colibri.loc/upload/default/avatar.png",…},
				"owner":{"id": 7, "url": "http://colibri.loc/@dan_kassing", "avatar": "http://colibri.loc/upload/default/avatar.png",…},
				"offset_id": 41
			},
			"next":[
				{
					"id": 42,
					"user_id": 7,
					"text": "werwe",
					"type": "text",
					"replys_count": "0",
					"reposts_count": "0",
					"likes_count": "0",
					"status": "active",
					"thread_id": 41,
					"target": "pub_reply",
					"og_data": "",
					"time": "18 seconds ago",
					"replys":[],
					"advertising": false,
					"time_raw": "1605613170",
					"og_text": "werwe",
					"og_image": "statics/img/logo.png",
					"url": "http://colibri.loc/thread/42",
					"can_delete": true,
					"media":[],
					"is_owner": true,
					"has_liked": false,
					"has_saved": false,
					"has_reposted": false,
					"reply_to":{"id": 7, "url": "http://colibri.loc/@dan_kassing", "avatar": "http://colibri.loc/upload/default/avatar.png",…},
					"owner":{"id": 7, "url": "http://colibri.loc/@dan_kassing", "avatar": "http://colibri.loc/upload/default/avatar.png",…},
					"offset_id": 42
				}
			],
			"prev":[
				{
					"id": 40,
					"user_id": 7,
					"text": "erter",
					"type": "text",
					"replys_count": "1",
					"reposts_count": "0",
					"likes_count": "0",
					"status": "active",
					"thread_id": 0,
					"target": "publication",
					"og_data": "",
					"time": "28 minutes ago",
					"advertising": false,
					"time_raw": "1605611503",
					"og_text": "erter",
					"og_image": "statics/img/logo.png",
					"url": "http://colibri.loc/thread/40",
					"can_delete": true,
					"media":[],
					"is_owner": true,
					"has_liked": false,
					"has_saved": false,
					"has_reposted": false,
					"reply_to":[],
					"owner":{"id": 7, "url": "http://colibri.loc/@dan_kassing", "avatar": "http://colibri.loc/upload/default/avatar.png",…},
					"offset_id": 40
				}
			]
		}
	}
	</code></pre>
	    </div>
	</div>
	<h4 class="table-title">错误响应</h4>
	<div class="code-holder">
	    <div class="code-holder-inner">
	<pre><code class="json">{
	    "code": 401,
	    "data": [],
	    "message": "未授权访问"
	}

	{
		"code": 400,
		"message": "帖子ID缺失或无效。请检查您的信息",
		"data": []
	}
	</code></pre>
	    </div>
	</div>
</div>