<div class="content__inner">
	<h2>加载帖子回复</h2>
	<p>
	    请使用此 <strong>(<?php echo cl_link("mobile_api/thread_replys"); ?>)</strong> API访问帖子线程回复端点
	</p>
	<h3>
		数据结构说明
	</h3>
	<br>
	<p>
		请注意，`data`数组中的每个帖子项也可以包含`replys`变量，其中包含对其的前几条回复（见上文）
	</p>
	<h4 class="table-title">GET参数</h4>
	<table class="table table-bordered">
	    <thead>
	    <tr>
	        <th width="15%">字段</th>
	        <th width="25%">值</th>
	        <th width="45%">说明</th>
	    </tr>
	    </thead>
	    <tbody>
	        <tr>
	            <td>session_id</td>
	            <td>​访问令牌ID</td>
	            <td>
	                例如: de25cc16eb00960f076...
	            </td>
	        </tr>
	        <tr>
	            <td>thread_id</td>
	            <td>帖子线程ID</td>
	            <td>
	                例如: 123456（任何帖子的ID，用于查看回复和所有详情）
	            </td>
	        </tr>
	        <tr>
	            <td>page_size</td>
	            <td>​每次请求的帖子总数限制（可选）</td>
	            <td>
	                推荐: 20
	            </td>
	        </tr>
	        <tr>
	            <td>offset</td>
	            <td>最后帖子偏移ID</td>
	            <td>
	                此变量必须是`next`数组中最后一个帖子（回复）对象的ID（见上文）
	            </td>
	        </tr>
	    </tbody>
	</table>
	<h4 class="table-title">成功响应</h4>
	<div class="code-holder">
	    <div class="code-holder-inner">
	<pre><code class="json">{
		"message": "回复获取成功",
		"code": 200,
		"data":[
			{
				"id": 44,
				"user_id": 7,
				"text": "sdfrw",
				"type": "text",
				"replys_count": "0",
				"reposts_count": "0",
				"likes_count": "0",
				"status": "active",
				"thread_id": 41,
				"target": "pub_reply",
				"og_data": "",
				"time": "50 minutes ago",
				"replys":[],
				"advertising": false,
				"time_raw": "1605617624",
				"og_text": "sdfrw",
				"og_image": "statics/img/logo.png",
				"url": "http://colibri.loc/thread/44",
				"can_delete": true,
				"media":[],
				"is_owner": true,
				"has_liked": false,
				"has_saved": false,
				"has_reposted": false,
				"reply_to":{"id": 7, "url": "http://colibri.loc/@dan_kassing", "avatar": "http://colibri.loc/upload/default/avatar.png",…},
				"owner":{"id": 7, "url": "http://colibri.loc/@dan_kassing", "avatar": "http://colibri.loc/upload/default/avatar.png",…},
				"offset_id": 44
			},
			{
				"id": 43,
				"user_id": 7,
				"text": "sdf",
				"type": "text",
				"replys_count": "0",
				"reposts_count": "0",
				"likes_count": "0",
				"status": "active",
				"thread_id": 41,
				"target": "pub_reply",
				"og_data": "",
				"time": "50 minutes ago",
				"replys":[],
				"advertising": false,
				"time_raw": "1605617612",
				"og_text": "sdf",
				"og_image": "statics/img/logo.png",
				"url": "http://colibri.loc/thread/43",
				"can_delete": true,
				"media":[],
				"is_owner": true,
				"has_liked": false,
				"has_saved": false,
				"has_reposted": false,
				"reply_to":{"id": 7, "url": "http://colibri.loc/@dan_kassing", "avatar": "http://colibri.loc/upload/default/avatar.png",…},
				"owner":{"id": 7, "url": "http://colibri.loc/@dan_kassing", "avatar": "http://colibri.loc/upload/default/avatar.png",…},
				"offset_id": 43
			}
		]
	}
	</code></pre>
	    </div>
	</div>
	<h4 class="table-title">错误响应</h4>
	<div class="code-holder">
	    <div class="code-holder-inner">
	<pre><code class="json">{
	    "code": 401,
	    "data": [],
	    "message": "未授权访问"
	}

	{
		"message": "未找到数据",
		"code": 404,
		"data": []
	}

	{
		"code": 400,
		"message": "帖子ID缺失或无效。请检查您的信息",
		"data": []
	}

	{
		"code": 400,
		"message": "分页偏移ID缺失或无效。请检查您的信息",
		"data": []
	}
	</code></pre>
	    </div>
	</div>
</div>