<div class="content__inner">
    <h2>刷新访问令牌</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/refresh_access_token"); ?>)</strong> API访问用户访问令牌管理端点
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>​refresh_token</td>
                <td>​刷新令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "令牌刷新成功",
        "data":{
            "auth_token": "bc93431b2120eb63650e69a526ca100a355cd3871605119043bc611a7b1496e204c6b9869d0cb0bbb1",
            "refresh_token": "37d5bf2ebd34d49a3fa2d3f146486c0b1605119043ae30694f74bc5535becb59eb23121ad9",
            "auth_token_expiry": 1636655043
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 400,
        "message": "令牌值无效或用户账户已禁用",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>