<div class="cp-app-container" data-app="email-settings">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                邮件设置 (SMTP)
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        管理邮件系统设置
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form1">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group" data-an="smtp_username-input">
                                    <label>
                                        SMTP username
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config smtp_username%}" name="smtp_username" type="text" class="form-control" placeholder="Enter the username of your SMTP server">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group" data-an="smtp_host-input">
                                    <label>
                                        SMTP host
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config smtp_host%}" name="smtp_host" type="text" class="form-control" placeholder="Enter the host name of your SMTP server">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group" data-an="smtp_password-input">
                                    <label>
                                        SMTP password
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config smtp_password%}" name="smtp_password" type="passwords" class="form-control" placeholder="Enter the password of your SMTP server">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group" data-an="smtp_encryption-input">
                                    <label>
                                        SMTP encryption
                                    </label>
                                    <div class="form-line form-select">
                                        <select name="smtp_encryption" class="form-control">
                                            <option value="ssl" <?php if($cl['config']['smtp_encryption'] == 'ssl') { echo('selected'); } ?>>SSL</option>
                                            <option value="tls" <?php if($cl['config']['smtp_encryption'] == 'tls') { echo('selected'); } ?>>TLS</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group" data-an="smtp_or_mail-input">
                                    <label>
                                        Mail server (SMTP or Mail)
                                    </label>
                                    <div class="form-line form-select">
                                        <select name="smtp_or_mail" class="form-control">
                                            <option value="smtp" <?php if($cl['config']['smtp_or_mail'] == 'smtp') { echo('selected'); } ?>>SMTP</option>
                                            <option value="mail" <?php if($cl['config']['smtp_or_mail'] == 'mail') { echo('selected'); } ?>>MAIL</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group" data-an="smtp_port-input">
                                    <label>
                                        SMTP port
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config smtp_port%}" name="smtp_port" type="number" class="form-control" placeholder="Enter the port of your SMTP server">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 no-mb">
                                <div class="form-group no-mb">
                                    <button data-an="submit-ctrl" type="submit" class="btn btn-primary">
                                        保存更改
                                    </button>
                                    <hr>
                                    <small class="info-feedback">
                                        <p>
                                            如果您输入了SMTP服务器的凭据，但仍然无法发送电子邮件，请尝试如下所示的组合
                                        </p>
                                        <ol>
                                            <li>
                                                SMTP encryption: <b>SSL</b> with SMTP port: <b>465</b>
                                            </li>
                                            <li>
                                                SMTP encryption: <b>TLS</b> with SMTP port: <b>587</b>
                                            </li>
                                        </ol>
                                    </small>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        检查（SMTP）服务器
                    </h2>
                </div>
                <div class="body">
                    <div class="inline-alertbox-wrapper">
                        <div class="inline-alertbox info">
                            <div class="icon">
                                <?php echo cl_ficon("info"); ?>
                            </div>
                            <div class="alert-message">
                                <p>
                                    请注意，在保存您的SMTP凭据后，验证您的SMTP服务器是否正在工作对您来说非常重要
                                    <br><br>

                                    使用此功能向下面的电子邮件地址发送测试电子邮件，以确保您的SMTP已设置并正在工作
                                </p>
                            </div>
                        </div>
                    </div>
                    <form class="form" data-an="form2">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group" data-an="test_email-input">
                                    <label>
                                        E-Mail address
                                    </label>
                                    <div class="form-line">
                                        <input name="test_email" type="text" class="form-control" placeholder="Enter a email address">
                                    </div>
                                    <small class="info-feedback">
                                        <p>
                                            输入将发送测试消息的电子邮件地址
                                        </p>
                                    </small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 no-mb">
                                <div class="form-group no-mb">
                                    <button data-an="submit-ctrl" type="submit" class="btn btn-primary">
                                        Send test message
                                    </button>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo cl_template('cpanel/assets/email_settings/scripts/app_master_script'); ?>