<div class="content__inner">
    <h2>添加书签/取消书签</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/add_bookmark"); ?>)</strong> API访问添加书签/取消书签帖子端点
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>post_id</td>
                <td>要添加/取消书签的帖子整数ID</td>
                <td>
                    例如: 4567
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    	"code": 200,
    	"message": "",
    	"data": {
    		"bookmark": false
    	}
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
    	"code": 400,
    	"message": "帖子ID缺失或无效",
    	"data": []
    }
    </code></pre>
        </div>
    </div>
</div>