<div class="content__inner">
    <h2>获取书签</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/get_bookmarks"); ?>)</strong> API访问获取用户书签端点
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>每次请求的帖子总数限制</td>
                <td>
                    推荐值：20
                </td>
            </tr>
            <tr>
                <td>offset</td>
                <td>最后帖子偏移ID</td>
                <td>
                    仅在加载分页系统的帖子时需要。
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "书签获取成功",
        "data":[
            {"id": 36, "user_id": 7, "text": "retw", "type": "text", "replys_count": "1",…},
            {"id": 38, "user_id": 7, "text": "ert", "type": "text",…},
            {"id": 39, "user_id": 7, "text": "ert", "type": "text",…},
            {"id": 40, "user_id": 7, "text": "erter", "type": "text",…}
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 204,
        "message": "未找到数据",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>