<div class="content__inner">
    <h2>上传帖子媒体</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/upload_post_media"); ?>)</strong> API端点上传帖子多媒体文件
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>type</td>
                <td>媒体文件类型 (image/video)</td>
                <td>
                    例如: image
                </td>
            </tr>
            <tr>
                <td>file</td>
                <td>媒体文件 (图片/视频)</td>
                <td>
                    例如: some-selfy-picture.jpeg
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应 (图片上传)</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    	"message": "媒体文件上传成功",
    	"code": 200,
    	"data": {
    		"media_id": 4,
    		"url": "新上传媒体文件的绝对URL",
    		"type": "图片/视频"
    	}
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">成功响应 (视频上传)</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    	"message": "媒体文件上传成功",
    	"code": 200,
    	"data": {
        	"media_id": 18,
        	"type": "视频",
        	"source": "新上传视频文件的绝对URL",
        	"poster": "自动生成的视频缩略图文件的绝对URL"
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
    	"code": 500,
    	"message": "媒体文件缺失或无效",
    	"data": []
    }


    {
    	"code": 400,
    	"message": "媒体文件类型缺失或无效",
    	"data": []
    }

    {
    	"code": 400,
    	"message": "一个帖子不能附加超过10张图片",
    	"data": []
    }

    {
    	"code": 500,
    	"message": "处理您的请求时发生错误。请稍后再试。",
    	"data": []
    }
    </code></pre>
        </div>
    </div>
</div>