<div class="content__inner">
    <h2>获取隐私设置</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/get_priv_settings"); ?>) API访问用户隐私设置端点</strong> 
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "",
        "data":{
            "profile_visibility": "everyone",
            "contact_privacy": "everyone",
            "follow_privacy": "everyone",
            "search_visibility": true
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }
    </code></pre>
        </div>
    </div>
</div>