<div class="content__inner">
    <h2>修改隐私设置</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/set_priv_settings"); ?>) API访问修改用户隐私设置端点</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>profile_visibility</td>
                <td>资料访问权限</td>
                <td>
                    例如: 以下选项之一 (followers/everyone)
                </td>
            </tr>
            <tr>
                <td>contact_privacy</td>
                <td>私信权限</td>
                <td>
                    例如: 以下选项之一 (followed/everyone)
                </td>
            </tr>
            <tr>
                <td>follow_privacy</td>
                <td>关注请求权限</td>
                <td>
                    例如: 以下选项之一 (approved/everyone)
                </td>
            </tr>
            <tr>
                <td>search_visibility</td>
                <td>资料搜索索引权限</td>
                <td>
                    例如: 以下选项之一 (Y/N)
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "用户隐私设置已更新",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "data": [],
        "message": "请求数据无效"
    }
    </code></pre>
        </div>
    </div>
</div>