<div class="content__inner">
    <h2>清除聊天/删除</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/clear_chat"); ?>) API访问清除和删除聊天历史的端点</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>对话者用户ID</td>
                <td>
                    例如: 4567
                </td>
            </tr>
            <tr>
                <td>delete_chat</td>
                <td>清除后删除聊天</td>
                <td>
                    例如: 以下选项之一（1/0）
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "聊天删除成功",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "message": "对话者ID缺失或无效",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>