<div class="content__inner">
    <h2>删除消息</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/delete_message"); ?>) API访问删除聊天消息的端点</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>message_id</td>
                <td>要删除的消息ID</td>
                <td>
                    例如: `34`
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "消息删除成功",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "message": "消息ID缺失或无效",
        "data": []
    }

    {
        "code": 400,
        "message": "未找到具有此ID的消息。请检查您的详细信息！",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>