<div class="content__inner">
    <h2>获取聊天</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/get_chats"); ?>) API访问聊天列表端点</strong> 
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "聊天获取成功",
        "data": [
            {
            "user_id": 78,
            "username": "mansurTLs",
            "name": "名字 姓氏",
            "avatar": "http://colibri.loc/upload/default/avatar.png",
            "verified": "0",
            "chat_id": 9,
            "time": "17分钟前",
            "last_message": "y",
            "new_messages": "",
            "chat_url": "http://colibri.loc/conversation/@mansurTLs"
            },
            {"user_id": 34, "username": "jack_nelson", "name": "Jack Nelson", "avatar": "http://colibri.loc/upload/default/avatar.png",…}
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }
    </code></pre>
        </div>
    </div>
</div>