<div class="content__inner">
    <h2>获取消息</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/get_messages"); ?>) API访问消息列表端点</strong> 
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>对话者用户ID</td>
                <td>
                    例如: 4567
                </td>
            </tr>
            <tr>
                <td>offset_up</td>
                <td>第一条消息偏移ID</td>
                <td>
                    仅在加载当前聊天的旧消息时需要。
                </td>
            </tr>
            <tr>
                <td>offset_down</td>
                <td>最后一条消息偏移ID</td>
                <td>
                    仅在加载当前聊天的新消息时需要。
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>每次请求的消息总数限制</td>
                <td>
                    推荐: 20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "data": [
            {
                "id": 86,
                "sent_by": 7,
                "sent_to": 78,
                "owner": true,
                "message": "1",
                "media_file": "",
                "media_type": "none",
                "seen": "0",
                "deleted_fs1": "N",
                "deleted_fs2": "N",
                "time": "2020年11月22日 10:11",
                "side": "right"
            },
            {...}
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "message": "对话者ID缺失或无效",
        "data": []
    }

    {
        "code": 204,
        "message": "未找到数据",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>