<div class="content__inner">
    <h2>发送消息/图片</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/send_message"); ?>) API访问发送消息的端点</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>对话者用户ID</td>
                <td>
                    例如: 4567
                </td>
            </tr>
            <tr>
                <td>type</td>
                <td>消息类型（文本或图片）</td>
                <td>
                    例如: 以下选项之一（text/media）
                </td>
            </tr>
            <tr>
                <td>image</td>
                <td>消息图片文件</td>
                <td>
                    例如: some-picture.jpeg
                </td>
            </tr>
            <tr>
                <td>message</td>
                <td>消息文本（最大长度3000）</td>
                <td>
                    例如: `嗨！你好吗？`
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    	"code": 200,
    	"message": "消息已发送",
    	"data": {
    		"id": 49,
    		"sent_by": 7,
    		"sent_to": 78,
    		"owner": true,
    		"message": "图片",
    		"media_file": "http://colibri.loc/upload/images/2020/11/lbEG1WesAJdnqVWuUVSd_21_00ae49e181b4a21f86d2338eed424e7b_image_original.jpg",
    		"media_type": "image",
    		"seen": "0",
    		"deleted_fs1": "N",
    		"deleted_fs2": "N",
    		"time": "2020年11月21日 03:11",
    		"side": "right",
    		"media_name": "COLIBRI-IMG-1605960603"
    	}
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
    	"code": 400,
    	"message": "对话者ID缺失或无效",
    	"data": []
    }

    {
    	"code": 400,
    	"message": "你没有权限向此聊天发送直接消息",
    	"data": []
    }

    {
    	"code": 400,
    	"message": "你的账户已被此账户屏蔽",
    	"data": []
    }

    {
    	"code": 500,
    	"message": "处理请求时发生错误。请稍后再试。",
    	"data": []
    }

    {
    	"code": 400,
    	"message": "消息的媒体类型无效或缺失",
    	"data": []
    }
    </code></pre>
        </div>
    </div>
</div>