<div class="content__inner">
    <h2>删除动态媒体</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/delete_swift_media"); ?>)</strong> API端点删除动态媒体文件
    </p>
    <p>
        在这种情况下，您只需发送上述请求即可删除动态媒体文件，即无需附加参数的请求，因为系统会自行判断最后上传的文件并将其删除
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "data": [],
        "message": "媒体删除成功"
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }
    </code></pre>
        </div>
    </div>
</div>