<div class="content__inner">
    <h2>获取我的动态列表</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/get_swifts"); ?>)</strong> API端点获取用户动态列表
    </p>
    <p>
        此端点将允许您获取登录用户的所有活跃动态
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "data":[
            {
                "id": 5,
                "username": "@admin",
                "fname": "Mansur",
                "lname": "ATL",
                "avatar": "http://colibri.loc/upload/avatars/xx/xx/ZIGRH9xMQ5YXeo7s1FtI_....._thumbnail_512x512.jpeg",
                "swift":[
                    {
                        "views":[
                            "1": {
                                "id": 1,
                                "username": "@testuser",
                                "fname": "Admin",
                                "lname": "O'user",
                                "avatar": "http://colibri.loc/upload/avatars/xx/xx/ZyoImsndzRPftd1UbMW5_24_3126....e6_thumbnail_512x512.jpg",
                                "name": "Admin O'user",
                                "url": "http://colibri.loc/@testuser",
                                "time": "24秒前"
                            }
                        ],
                        "time": "19:24",
                        "type": "image",
                        "status": "active",
                        "media":{
                            "src": "http://colibri.loc/upload/images/xx/xx/lr4UGK....54450_image_swift.png"
                        },
                        "exp_time": 1623947062,
                        "text": "",
                        "seen": 0,
                        "swid": "uNpuf6SrlRzQ3xVg"
                    }
                ],
                "name": "Mansur ATL",
                "url": "http://colibri.loc/@admin",
                "is_user": true,
                "has_unseen": false
            }
        ],
        "message": "动态获取成功"
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 404,
        "data": [],
        "message": "暂无动态可用"
    }
    </code></pre>
        </div>
    </div>
</div>