<div class="content__inner">
    <h2>发布动态</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/publish_swift"); ?>)</strong> API端点发布动态
    </p>
    <p>
        创建动态的此阶段假设您已经上传了媒体文件，即动态的视频或图片。由于创建动态时需要媒体文件，而描述则可选，您可以选择是否发送描述。
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>swift_text</td>
                <td>文本消息（最多200字符）</td>
                <td>
                    例如: `Lorem ipsum`
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "动态发布成功",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }
    </code></pre>
        </div>
    </div>
</div>