<div class="content__inner">
    <h2>注册Swift视图</h2>
    <p>
        请使用此<strong>(<?php echo cl_link("mobile_api/reg_swift_view"); ?>)</strong> API端点来注册Swift视图
    </p>
    <p>
        当Swift被打开时，需要使用此端点向服务器发送请求，以便系统记录Swift视图。
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如：de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>Swift用户ID</td>
                <td>
                    例如：`10`
                </td>
            </tr>
            <tr>
                <td>swid</td>
                <td>Swift哈希ID</td>
                <td>
                    例如：`zpad2HalsbsLGhdI`
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "Swift视图注册成功",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "data":[],
        "message": "用户ID无效或缺失"
    }
    </code></pre>
        </div>
    </div>
</div>