<div class="content__inner">
    <h2>搜索用户</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/search_people"); ?>)</strong> API 访问用户搜索端点
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>query</td>
                <td>搜索关键词</td>
                <td>
                    例如: John Smith
                </td>
            </tr>
            <tr>
                <td>offset</td>
                <td>最后帖子偏移ID</td>
                <td>
                    仅在加载分页系统的帖子时需要。
                </td>
            </tr>
            <tr>
                <td>session_id (可选)</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>每次请求的帖子总数限制</td>
                <td>
                    推荐: 20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "找到结果",
        "data":[
            {
                "id": 78,
                "about": "",
                "followers": 0,
                "posts": 0,
                "avatar": "http://colibri.loc/upload/default/avatar.png",
                "last_active": "2020年9月29日 上午11:09",
                "username": "@mansurTLs",
                "fname": "名字",
                "lname": "姓氏",
                "email": "jovogals@gmail.com",
                "verified": "0",
                "name": "名字 姓氏",
                "url": "http://colibri.loc/@mansurTLs",
                "is_user": false,
                "is_following": false
            }
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 204,
        "message": "未找到数据",
        "data": []
    }

    {
        "code": 400,
        "message": "搜索词无效或缺失",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>