<div class="content__inner">
    <h2>关注与取消关注用户</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/follow"); ?>) API访问（关注/取消关注）用户端点</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>已关注/已取消关注的用户整数ID</td>
                <td>
                    例如: 4567
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "关注成功",
        "data":{
            "follow": true
        }
    }

    {
        "code": 200,
        "message": "取消关注成功",
        "data":{
            "follow": false
        }
    }

    {
        "code": 201,
        "message": "关注请求发送成功",
        "data":{
            "follow": false
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "message": "用户ID缺失或无效",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>