<div class="cp-app-container" data-app="withdrawal-requests">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                提现请求
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card" id="vue-cpanel-withdrawal-requests-app">
                <div class="header">
                    <h2>
                        用户钱包提现请求 - ({{total_requests}})
                    </h2>
                </div>
                <div class="body">
                    <div class="regular-table">
                        <table class="table table-hover no-mb">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        用户名
                                    </th>
                                    <th>
                                        E-mail 地址
                                    </th>
                                    <th>
                                        支付方式
                                    </th>
                                    <th>
                                        金额
                                    </th>
                                    <th>
                                        请求时间
                                    </th>
                                    <th>
                                        操作
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-an="requests-list">
                                <?php if (not_empty($cl['requests'])): ?>
                                    <?php foreach ($cl['requests'] as $cl['li']): ?>
                                        <?php echo cl_template('cpanel/assets/withdrawal_requests/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="7">
                                            <div class="empty-table">
                                                <h4>
                                                    未找到任何请求
                                                </h4>
                                                <p>
                                                  看起来您的数据库中还没有用户钱包的提现请求。<br>所有提现请求都将在这里显示  
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                        <div class="table-pagination">
                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_prev_ctrl}" v-on:click="paginate('up')" href="javascript:void(0);" class="pagination-ctrls prev">
                                <?php echo cl_ficon("arrow_left"); ?>
                            </a>

                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_next_ctrl}" v-on:click="paginate('down')" href="javascript:void(0);" class="pagination-ctrls next">
                                <?php echo cl_ficon("arrow_right"); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/withdrawal_requests/scripts/app_master_script'); ?>