<div class="content__inner">
    <h2>屏蔽用户资料</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/block_user"); ?>) API访问用户资料屏蔽端点</strong> 
    </p>
    <h5 class="text-red">
        <b>重要！</b>
    </h5>
    <p>
        请注意，如果再次请求此 API，用户将被解除屏蔽。即，第一次调用屏蔽，第二次调用解除屏蔽
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>用户整数ID</td>
                <td>
                    例如: 12
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">屏蔽成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    "code": 200,
    "message": "用户资料屏蔽成功",
    "data": []
}
</code></pre>
        </div>
    </div>
    <h4 class="table-title">解除屏蔽成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    "code": 200,
    "message": "用户资料解除屏蔽成功",
    "data": []
}
</code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    "code": 401,
    "data": [],
    "message": "未授权访问"
}

{
    "code": 400,
    "message": "用户ID缺失或无效",
    "data": []
}
</code></pre>
        </div>
    </div>
</div>
