<script>
	"use strict";

	$(document).ready(function($) {
		var _app  = $('[data-app="posts-censor-settings"]');
		var _data = _app.find('form[data-an="form"]');

		_data.ajaxForm({
			url: '<?php echo cl_link("native_api/cpanel/post_censor_settings"); ?>',
			type: 'POST',
			dataType: 'json',
			beforeSend: function() {
				_data.find('small.invalid-feedback').remove();
				_data.find('[data-an="submit-ctrl"]').attr('disabled', 'true').text("Please wait");
			},
			success: function(data) {
				if (data.status == 200) {
					cl_bs_notify("您的更改已成功保存！", 3000);
				}
				else {
					cl_bs_notify("尝试在本地数据库中存储审查词汇列表时出错。请确保文件：（core/loc_db/censor_words.csv）可写", 7000, "危险");
				}
			},
			complete: function() {
				_data.find('[data-an="submit-ctrl"]').removeAttr('disabled').text("Save changes");
			}
		});
	});
</script>