<div class="content__inner">
    <h2>用户登录</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/login"); ?>)</strong> API 访问用户登录端点
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>email</td>
                <td>用户电子邮箱地址</td>
                <td>
                    例如: mansurTL@gmail.com
                </td>
            </tr>
            <tr>
                <td>password</td>
                <td>用户密码</td>
                <td>
                    例如: 123456
                </td>
            </tr>
            <tr>
                <td>device_type</td>
                <td>客户端设备类型</td>
                <td>
                    ios/android（默认为android）
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "用户登录成功",
        "data": {
            "id": 7,
            "first_name": "Dan",
            "last_name": "Kassing",
            "user_name": "dan_kassing",
            "email": "dan_kassing@gmail.com",
            "is_verified": true,
            "website": "",
            "about_you": "",
            "gender": "M",
            "country": "美国",
            "post_count": 4045,
            "last_post": 0,
            "last_ad": 0,
            "language": "english",
            "following_count": 1,
            "follower_count": 3512,
            "wallet": "323.56",
            "ip_address": "127.0.0.1",
            "last_active": "1601382349",
            "member_since": "2020年7月",
            "profile_privacy": "followers"
        },
        "auth": {
            "auth_token": "c625cc16eb00960f076c1378c7b84ede29c01ed516013823754d476ebd93c709a1bb49b39eba40738a",
            "refresh_token": "de25cc16eb00960f076c1378c7b84ede29c01ed516013823754d476ebd93c709a1bb49b39eba40738a",
            "auth_token_expiry": 1916742375
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 402,
        "message": "凭据不正确",
        "data": []
    }

    {
        "code": 402,
        "message": "设备类型不正确",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>