<div class="cp-app-container" data-app="premium-account">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                高级账户设置
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        管理高级账户系统设置
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group" data-an="premium_account_mprice-input">
                                    <label>
                                        高级账户月费 (<b><?php echo strtoupper($cl["config"]["site_currency"]); ?></b>)
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config premium_account_mprice%}" name="premium_account_mprice" type="text" class="form-control" placeholder="PremiE.g. 10">
                                    </div>
                                    <small class="info-feedback">
                                        支付高级账户订阅费将从用户的钱包中扣除
                                    </small>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group" data-an="prem_account_system_status-input">
                                    <label>
                                        高级账户系统状态
                                    </label>
                                    <div class="form-line form-select">
                                        <select name="prem_account_system_status" class="form-control">
                                            <option value="on" <?php if($cl['config']['prem_account_system_status'] == 'on') { echo('selected'); } ?>>
                                                Enabled
                                            </option>
                                            <option value="off" <?php if($cl['config']['prem_account_system_status'] == 'off') { echo('selected'); } ?>>
                                                Disabled
                                            </option>
                                        </select>
                                    </div>  
                                    <small class="info-feedback">
                                        <b>重要提示：</b> 如果您禁用此功能，用户将无法购买或续订高级账户订阅，但之前购买的所有当前订阅将保持有效，直到它们到期
                                    </small>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 no-mb">
                                <button data-an="submit-ctrl" type="submit" class="btn btn-primary">
                                    保存更改
                                </button>
                            </div>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo cl_template('cpanel/assets/premium_account/scripts/app_master_script'); ?>