<div class="cp-app-container" data-app="google-ads">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                谷歌广告联盟
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        管理（谷歌广告联盟）系统设置
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group" data-an="google_ad_horiz-input">
                                    <label>
                                        水平广告横幅
                                    </label>
                                    <div class="form-line">
                                        <textarea name="google_ad_horiz" class="form-control" rows="2" placeholder="Enter a JS for horizontal ads banner" spellcheck="false">{%config google_ad_horiz%}</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group" data-an="google_ad_vert-input">
                                    <label>
                                        垂直广告横幅
                                    </label>
                                    <div class="form-line">
                                        <textarea name="google_ad_vert" class="form-control" rows="2" placeholder="Enter a JS for vertical ads banner" spellcheck="false">{%config google_ad_vert%}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 no-mb">
                                <button data-an="submit-ctrl" type="submit" class="btn btn-primary">
                                    保存更改
                                </button>
                            </div>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'], 'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/google_ads/scripts/app_master_script'); ?>