<div class="content__inner">
    <h2>删除关注请求</h2>
    <p>
        请使用此<strong>(<?php echo cl_link("mobile_api/ignore_follow"); ?>) API来访问用户关注请求删除的端点，即忽略请求</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID（可选）</td>
                <td>
                    例如：de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>req_id</td>
                <td>关注请求整数ID</td>
                <td>
                    例如：34
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "message": "关注请求已成功删除",
        "code": 200,
        "data": {
            "total": 0
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "message": "关注请求ID缺失或无效",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>