<div class="content__inner">
    <h2>获取关注请求</h2>
    <p>
        请使用此<strong>(<?php echo cl_link("mobile_api/follow_requests"); ?>) API来访问用户关注请求列表的端点</strong> 
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>offset</td>
                <td>最后用户偏移ID</td>
                <td>
                    只有在加载分页系统的用户时才需要。
                </td>
            </tr>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID（可选）</td>
                <td>
                    例如：de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>每个请求的用户总数限制</td>
                <td>
                    推荐：20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "关注请求获取成功",
        "data": [
            {
                "offset_id": 43,
                "id": 18,
                "about": "",
                "posts": 1,
                "avatar": "http://colibri.loc/upload/avatars/xxx/xxx/rddNMSoS6S7cEgHO49Ch_20_45...b8_thumbnail_512x512.jpg",
                "last_active": "21 Jun, 21 02:06 PM",
                "username": "@john_smith",
                "fname": "John",
                "lname": "Smith",
                "email": "john_smith@gmail.com",
                "verified": "0",
                "name": "John Smith",
                "url": "http://colibri.loc/@john_smith",
                "pending_req": true
            },
            {...}
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 204,
        "message": "未找到数据",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>