<div class="content__inner">
    <h2>更改显示语言</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/language"); ?>) API端点更改显示语言</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>lang_name</td>
                <td>显示语言名称</td>
                <td>
                    例如: 以下选项之一 (english 英语, french 法语, german 德语, italian 意大利语, russian 俄语, portuguese 葡萄牙语, spanish 西班牙语, turkish 土耳其语, dutch 荷兰语, ukraine 乌克兰语)
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    	"code": 200,
    	"message": "语言更改成功",
    	"data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
    	"code": 400,
    	"message": "显示语言名称无效或缺失",
    	"data": []
    }
    </code></pre>
        </div>
    </div>
</div>