<div class="content__inner">
    <h2>修改密码</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/change_password"); ?>)</strong> API访问用户密码管理端点
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>old_password</td>
                <td>用户旧密码</td>
                <td>
                    例如: 123456
                </td>
            </tr>
            <tr>
                <td>new_password</td>
                <td>用户新密码</td>
                <td>
                    例如: secret123
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "密码已修改",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 402,
        "message": "旧密码不正确",
        "data": []
    }

    {
        "code": 402,
        "message": "新密码不正确",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>