<div class="cp-app-container" data-app="posts">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                发布
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        管理网站发布内容
                    </h2>
                </div>
                <div class="body">
                    <div class="regular-table">
                        <table class="table table-hover no-mb">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        帖子类型
                                    </th>
                                    <th>
                                        目标
                                    </th>
                                    <th>
                                        回复
                                    </th>
                                    <th>
                                        喜欢
                                    </th>
                                    <th>
                                        转发
                                    </th>
                                    <th>
                                        日期
                                    </th>
                                    <th>
                                        操作
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-an="posts-list">
                                <?php if (not_empty($cl['posts'])): ?>
                                    <?php foreach ($cl['posts'] as $cl['li']): ?>
                                        <?php echo cl_template('cpanel/assets/publications/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="8">
                                            <div class="empty-table">
                                                <h4>
                                                    没有找到帖子
                                                </h4>
                                                <p>
                                                    看起来您的数据库中还没有帖子。您网站的所有发布内容都将在这里显示
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                        <div class="table-pagination">
                            <?php if (not_empty($cl['posts'])): ?>
                                <a data-an="pagination" data-dir="prev" href="javascript:void(0);" class="pagination-ctrls prev">
                                    <?php echo cl_ficon("arrow_left"); ?>
                                </a>
                                <a data-an="pagination" data-dir="next" href="javascript:void(0);" class="pagination-ctrls next">
                                    <?php echo cl_ficon("arrow_right"); ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/publications/scripts/app_master_script'); ?>