<div class="cp-app-container" data-app="backups">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                备份
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        管理网站（文件和数据库）备份
                    </h2>
                </div>
                <div class="body">
                    <div class="inline-alertbox-wrapper">
                        <div class="inline-alertbox warning">
                            <div class="icon">
                                <?php echo cl_ficon("warning"); ?>
                            </div>
                            <div class="alert-message">
                                <p>
                                    请注意：在开始创建网站备份副本的过程之前，必须在服务器上安装PHP的ZipArchive模块，并确保您的网站的根目录可以被HTTP web服务器用户（www-data）写入，否则，备份过程将失败！

                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="inline-alertbox-wrapper">
                        <div class="inline-alertbox info">
                            <div class="icon">
                                <?php echo cl_ficon("info"); ?>
                            </div>
                            <div class="alert-message">
                                <p>
请注意：创建备份可能需要一些时间，具体取决于您网站上内容的数量，因此，在点击（创建备份）按钮后，请等待过程完成，不要离开该页面！
                                </p>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <form class="form" data-an="form">
                        <div class="form-group">
                            <?php if (not_empty($cl['config']['last_backup'])): ?>
                                <h5>
                                    <span>
                                        上一次备份
                                    </span>
                                    <time data-an="last-backup-date">
                                        (<?php echo date('d F, Y - h:m', $cl['config']['last_backup']); ?>)
                                    </time>    
                                </h5>
                            <?php else: ?>
                                <h5>
                                    <span>上一次备份
</span>
                                    <time data-an="last-backup-date">(00/00/0000 - 00:00)</time>
                                </h5>
                            <?php endif; ?>
                        </div>
                        <div class="form-group no-mb">
                            <button data-an="submit-ctrl" type="submit" class="btn btn-primary">
                                创建备份
                            </button>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/backups/scripts/app_master_script'); ?>