<div class="content__inner">
    <h2>社交登录</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/oauth"); ?>)</strong> API访问用户社交（oAuth2 API）登录端点
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>access_token</td>
                <td>API访问令牌</td>
                <td>
                    例如: ya29.a0AfH6SMBPzaEI2NaZyo_sui...
                </td>
            </tr>
            <tr>
                <td>type</td>
                <td>API提供商名称</td>
                <td>
                    例如: `facebook` 或 `google`
                </td>
            </tr>
            <tr>
                <td>device_type</td>
                <td>客户端设备类型</td>
                <td>
                    ios/android（默认为android）
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "用户登录成功",
        "data": {
            "id": 7,
            "first_name": "Dan",
            "last_name": "Kassing",
            "user_name": "dan_kassing",
            "email": "dan_kassing@gmail.com",
            "is_verified": true,
            "website": "",
            "about_you": "",
            "gender": "M",
            "country": "美国",
            "post_count": 4045,
            "last_post": 0,
            "last_ad": 0,
            "language": "english",
            "following_count": 1,
            "follower_count": 3512,
            "wallet": "323.56",
            "ip_address": "127.0.0.1",
            "last_active": "1601382349",
            "member_since": "2020年7月",
            "profile_privacy": "followers"
        },
        "auth": {
            "auth_token": "c625cc16eb00960f076c1378c7b84ede29c01ed516013823754d476ebd93c709a1bb49b39eba40738a",
            "refresh_token": "de25cc16eb00960f076c1378c7b84ede29c01ed516013823754d476ebd93c709a1bb49b39eba40738a",
            "auth_token_expiry": 1916742375
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 402,
        "message": "访问令牌无效或缺失",
        "data":[],
        "error": {
            "error": "invalid_request",
            "error_description": "Invalid Credentials"
        }
    }

    {
        "code": 400,
        "message": "oAuth提供商类型缺失或无效",
        "data": []
    }


    {
        "code": 500,
        "message": "API错误 - API不可用",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>