<div class="content__inner">
    <h2>举报用户资料</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/profile_report"); ?>) API访问用户资料举报端点</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>用户整数ID</td>
                <td>
                    例如: 12
                </td>
            </tr>
            <tr>
                <td>reason</td>
                <td>​
                    举报原因整数ID（此值必须为右侧所示的整数）
                    <br>
                    <br>
                    <div>
                        例如，如果你想举报垃圾账号，则此值应为 <b>1</b>
                    </div>
                </td>
                <td>
                    <ul>
                        <li>
                            1 = 此用户使用该账户发送垃圾内容
                        </li>
                        <li>
                            2 = 此用户冒充他人
                        </li>
                        <li>
                            3 = 此用户发布不当内容
                        </li>
                        <li>
                            4 = 这是一个虚假账号
                        </li>
                        <li>
                            5 = 这是一个欺诈账号
                        </li>
                        <li>
                            6 = 其他
                        </li>
                    </ul>
                </td>
            </tr>
            <tr>
                <td>comment</td>
                <td>​给审核人员的备注</td>
                <td>
                    `请采取相应措施。谢谢！`
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    "code": 200,
    "message": "举报已成功提交",
    "data": []
}
</code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
    "code": 401,
    "data": [],
    "message": "未授权访问"
}

{
    "code": 400,
    "message": "用户ID缺失或无效",
    "data": []
}

{
    "code": 400,
    "message": "举报原因ID缺失或无效",
    "data": []
}
</code></pre>
        </div>
    </div>
</div>
