<div class="content__inner">
    <h2>举报帖子</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/publication_report"); ?>) API访问帖子举报端点</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>​访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>post_id</td>
                <td>​帖子整数ID</td>
                <td>
                    例如: 4567
                </td>
            </tr>
            <tr>
                <td>reason</td>
                <td>​
                    举报原因整数ID（此值必须为右侧所示的整数）
                    <br>
                    <br>
                    <div>
                        例如，如果你想举报垃圾内容，则此值应为 <b>1</b>
                    </div>
                </td>
                <td>
                    <ul>
                        <li>
                            1 = 垃圾内容
                        </li>
                        <li>
                            2 = 误导性或欺诈性内容
                        </li>
                        <li>
                            3 = 发布私人信息
                        </li>
                        <li>
                            4 = 暴力威胁或人身伤害威胁
                        </li>
                        <li>
                            5 = 我对该帖子不感兴趣
                        </li>
                        <li>
                            6 = 其他
                        </li>
                    </ul>
                </td>
            </tr>
            <tr>
                <td>comment</td>
                <td>​给审核人员的备注</td>
                <td>
                    `请采取相应措施。谢谢！`
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "举报已成功提交",
        "data": []
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "message": "帖子ID缺失或无效",
        "data": []
    }

    {
        "code": 400,
        "message": "举报原因ID缺失或无效",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>
