<div class="content__inner">
    <h2>用户时间线动态</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/feeds"); ?>)</strong> API访问用户时间线动态端点
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>offset</td>
                <td>最后帖子偏移ID</td>
                <td>
                    仅在加载分页系统的帖子时需要。
                </td>
            </tr>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>每次请求的帖子总数限制</td>
                <td>
                    推荐: 20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "动态获取成功",
        "data": {
            "feeds": [
                {
                    "id": 238,
                    "user_id": 2,
                    "text": "lorejm egwtwer",
                    "type": "text",
                    "replys_count": "0",
                    "reposts_count": "0",
                    "likes_count": "0",
                    "status": "active",
                    "thread_id": 0,
                    "target": "publication",
                    "og_data": "",
                    "time": "9 hours ago",
                    "offset_id": 18,
                    "is_repost": false,
                    "is_reposter": false,
                    "attrs": "",
                    "advertising": false,
                    "time_raw": "1601368136",
                    "og_text": "lorejm egwtwer",
                    "og_image": "statics/img/logo.png",
                    "url": "http://colibri.loc/thread/238",
                    "can_delete": true,
                    "media": [],
                    "is_owner": false,
                    "has_liked": false,
                    "has_saved": false,
                    "has_reposted": false,
                    "reply_to": [],
                    "owner": {
                        "id": null,
                        "url": null,
                        "avatar": null,
                        "username": null,
                        "name": null,
                        "verified": null
                    }
                },
                {
                    "id": 237,
                    "user_id": 2,
                    "text": "",
                    "type": "gif",
                    "replys_count": "0",
                    "reposts_count": "0",
                    "likes_count": "0",
                    "status": "active",
                    "thread_id": 0,
                    "target": "publication",
                    "og_data": "",
                    "time": "9 hours ago",
                    "offset_id": 17,
                    "is_repost": false,
                    "is_reposter": false,
                    "attrs": "",
                    "advertising": false,
                    "time_raw": "1601368106",
                    "og_text": "",
                    "og_image": "statics/img/logo.png",
                    "url": "http://colibri.loc/thread/237",
                    "can_delete": true,
                    "media": [
                        {
                            "id": 14,
                            "pub_id": 237,
                            "type": "gif",
                            "src": "https://media3.giphy.com/media/IdmZ0ECRI5OzJZwEpT/giphy.gif",
                            "json_data": "[]",
                            "time": "1601368106",
                            "x": []
                        }
                    ],
                    "is_owner": false,
                    "has_liked": false,
                    "has_saved": false,
                    "has_reposted": false,
                    "reply_to": [],
                    "owner": {
                        "id": null,
                        "url": null,
                        "avatar": null,
                        "username": null,
                        "name": null,
                        "verified": null
                    },
                    "gif": null
                }
            ]
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }
    </code></pre>
        </div>
    </div>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "message": "未找到数据",
        "code": 204,
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>