<div class="content__inner">
    <h2>投票</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/vote_polls"); ?>) API端点进行投票</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>post_id</td>
                <td>帖子整数ID</td>
                <td>
                    例如: 84
                </td>
            </tr>
            <tr>
                <td>poll_id</td>
                <td>投票选项索引ID（从0,1,2,3等开始）</td>
                <td>
                    例如: 要投票给第一个选项，请发送 <b>0</b>
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "投票成功",
        "data":{
            "poll_data":{
                "has_voted": 1,
                "total": 1,
                "options":[
                    {
                        "percentage": "0",
                        "total": 0,
                        "option": "选项1"
                    },
                    {
                        "percentage": "100",
                        "total": 1,
                        "option": "选项2"
                    },
                    {
                        "percentage": "0",
                        "total": 0,
                        "option": "选项2"
                    }
                ]
            }
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 400,
        "message": "处理请求时发生错误",
        "data": []
    }

    {
        "code": 400,
        "message": "帖子ID缺失或无效",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>