<div class="content__inner">
    <h2>更改用户头像</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/avatar"); ?>)</strong> API访问用户头像上传端点
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>avatar</td>
                <td>图片格式文件 (jpg,png,jpeg,gif)</td>
                <td>
                    image.jpeg
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "头像更改成功",
        "data": {
            "avatar_url": "http://dev.colibri.loc/upload/avatars/2021/02/hVB4NV4....a967a7_thumbnail_512x512.jpg"
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "data": [],
        "message": "头像图片缺失或无效"
    }
    </code></pre>
        </div>
    </div>
</div>