<div class="content__inner">
    <h2>更改用户个人资料封面位置</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/cover_reposition"); ?>) API访问更改用户个人资料封面位置的端点</strong> 
    </p>
    <p>
        此访问点允许您上下更改个人资料封面的位置。边距从顶部到底部以像素为单位梳理，给定标准封面尺寸为600×200像素。
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>cover_position</td>
                <td>整数顶部位置偏移量</td>
                <td>
                    例如: 10
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "您的更改已成功保存",
        "data":{
            "cover_url": "http://dev.colibri.loc/upload/covers/2021/02/bp3lj5....ccd9c7_image_cover.jpg"
        }
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "data": [],
        "message": "封面位置偏移量缺失或无效"
    }
    </code></pre>
        </div>
    </div>
</div>