<div class="content__inner">
    <div class="content__inner">
        <h2>我的/用户资料数据</h2>
        <p>
            请使用此 <strong>(<?php echo cl_link("mobile_api/profile"); ?>)</strong> API访问用户资料数据获取端点
        </p>
        <br>
        <h4 class="table-title">GET参数</h4>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th width="15%">字段</th>
                <th width="25%">值</th>
                <th width="45%">说明</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>user_id</td>
                    <td>用户资料ID</td>
                    <td>
                        为了获取资料信息，您必须发送有效的ID或用户名
                    </td>
                </tr>
                <tr>
                    <td>username</td>
                    <td>用户资料用户名</td>
                    <td>
                        唯一用户名。例如："mansur_tl"
                    </td>
                </tr>
                <tr>
                    <td>session_id</td>
                    <td>用户认证令牌（可选）</td>
                    <td>
                        在这种情况下，不需要授权，但最好确定您是否订阅了此资料，是否被阻止等。
                    </td>
                </tr>
            </tbody>
        </table>
        <h4 class="table-title">成功响应</h4>
        <div class="code-holder">
            <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "资料获取成功",
        "data":{
            "id": 79,
            "first_name": "rwefwe",
            "last_name": "werwer",
            "avatar": "<?php echo cl_link("upload/avatars/2020/05/thumbnail_120x120.png"); ?>",
            "cover": "<?php echo cl_link("upload/covers/2020/11/image_cover.jpg"); ?>",
            "user_name": "3324",
            "email": "dan_kassings@gmail.com",
            "is_verified": false,
            "website": "",
            "about_you": "",
            "gender": "M",
            "country": "United States",
            "post_count": 0,
            "about": "",
            "ip_address": "127.0.0.1",
            "following_count": 0,
            "follower_count": 0,
            "language": "english",
            "last_active": "1601390105",
            "profile_privacy": "everyone",
            "member_since": "Sep 2020",
            "is_blocked_visitor": false,
            "is_following": false,
            "can_view_profile": true
        }
    }</code></pre>
            </div>
        </div>
        <h4 class="table-title">错误响应</h4>
        <div class="code-holder">
            <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 400,
        "message": "用户ID缺失或无效",
        "data": []
    }

    {
        "code": 400,
        "message": "用户ID缺失或无效",
        "data": []
    }
    </code></pre>
            </div>
        </div>
    </div>
</div>