<div class="content__inner">
    <h2>获取关注用户列表</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/fetch_following"); ?>) API 访问用户关注列表端点</strong> 
    </p>
    <br>
    <h4 class="table-title">GET参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>offset</td>
                <td>最后用户偏移ID</td>
                <td>
                    仅在加载分页系统的用户时需要。
                </td>
            </tr>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID (可选)</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>user_id</td>
                <td>用户整数ID</td>
                <td>
                    例如: 12
                </td>
            </tr>
            <tr>
                <td>page_size</td>
                <td>每次请求的用户总数限制</td>
                <td>
                    推荐: 20
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 200,
        "message": "关注列表获取成功",
        "data": [
            {
                "offset_id": 34,
                "id": 11,
                "about": "",
                "followers": 2,
                "posts": 0,
                "avatar": "http://colibri.loc/upload/avatars/xxx/xxx/AfPCXr9D7Gome6nAlwr...f15_thumbnail_512x512.png",
                "last_active": "2021年3月12日 晚上11:03",
                "username": "@defgdfg",
                "fname": "管理员",
                "lname": "用户",
                "email": "dfgdf@fdgdfg.com",
                "verified": "0",
                "follow_privacy": "所有人",
                "name": "管理员 用户",
                "url": "http:\/\/colibri.loc\/@defgdfg",
                "is_following": true,
                "follow_requested": false,
                "is_user": false
            },
            ...
        ]
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "message": "未找到数据",
        "code": 204,
        "data": []
    }

    {
        "code": 404,
        "message": "此ID的用户不存在",
        "data": []
    }

    {
        "code": 400,
        "message": "此个人资料数据不可查看",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>
