<div class="content__inner">
    <h2>删除通知和提及</h2>
    <p>
        请使用此 <strong>(<?php echo cl_link("mobile_api/delete_notifs"); ?>) API访问（通知和提及）删除端点</strong> 
    </p>
    <br>
    <h4 class="table-title">POST参数</h4>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th width="15%">字段</th>
            <th width="25%">值</th>
            <th width="45%">说明</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>session_id</td>
                <td>访问令牌ID</td>
                <td>
                    例如: de25cc16eb00960f076...
                </td>
            </tr>
            <tr>
                <td>scope</td>
                <td>通知ID数组（整数）</td>
                <td>
                    例如: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...]
                </td>
            </tr>
        </tbody>
    </table>
    <h4 class="table-title">成功响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "data": [],
        "code": 200,
        "message": "通知删除成功"
    }
    </code></pre>
        </div>
    </div>
    <h4 class="table-title">错误响应</h4>
    <div class="code-holder">
        <div class="code-holder-inner">
    <pre><code class="json">{
        "code": 401,
        "data": [],
        "message": "未授权访问"
    }

    {
        "code": 400,
        "message": "通知ID缺失或无效",
        "data": []
    }
    </code></pre>
        </div>
    </div>
</div>