<div class="cp-app-container" data-app="affiliate-payouts">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                联盟支付
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card" id="vue-cpanel-affiliate-payouts-app">
                <div class="header">
                    <h2>
                        管理联盟支付请求 - ({{total_requests}})
                    </h2>
                </div>
                <div class="body">
                    <div class="inline-alertbox-wrapper">
                        <div class="inline-alertbox info">
                            <div class="icon">
                                <?php echo cl_ficon("info"); ?>
                            </div>
                            <div class="alert-message">
                                <p>
                                    请注意：在处理支付或拒绝支付的情况时，务必通过电子邮件通知用户，告知他们请求的处理结果
                                </p>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="regular-table">
                        <table class="table table-hover no-mb">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        用户名
                                    </th>
                                    <th>
                                        E-mail address
                                    </th>
                                    <th>
                                        Paypal
                                    </th>
                                    <th>
                                        金额
                                    </th>
                                    <th>
                                        状态
                                    </th>
                                    <th>
                                        请求于
                                    </th>
                                    <th>
                                        操作
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-an="requests-list">
                                <?php if (not_empty($cl['requests'])): ?>
                                    <?php foreach ($cl['requests'] as $cl['li']): ?>
                                        <?php echo cl_template('cpanel/assets/affiliate_payouts/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="8">
                                            <div class="empty-table">
                                                <h4><?php echo('未找到请求'); ?></h4>
                                                <p>
                                                    <?php echo('目前您的数据库中似乎还没有联盟支付请求。所有联盟支付请求将会在此处展示'); ?>
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                        
                        <div class="table-pagination">
                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_prev_ctrl}" v-on:click="paginate('up')" href="javascript:void(0);" class="pagination-ctrls prev">
                                <?php echo cl_ficon("arrow_left"); ?>
                            </a>
                            <a v-if="show_ctrls" v-bind:class="{'disabled': dis_next_ctrl}" v-on:click="paginate('down')" href="javascript:void(0);" class="pagination-ctrls next">
                                <?php echo cl_ficon("arrow_right"); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo cl_template('cpanel/assets/affiliate_payouts/scripts/app_master_script'); ?>