<div class="cp-app-container" data-app="themes">
    <div class="current-page-name">
        <div class="lp">
            <h1>
                用户界面主题
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        管理用户界面主题
                    </h2>
                </div>
                <div class="body responsive">
                    <div class="inline-alertbox-wrapper">
                        <div class="inline-alertbox warning">
                            <div class="icon">
                                <?php echo cl_ficon("warning"); ?>
                            </div>
                            <div class="alert-message">
                                <p>
                                    请注意，为了正确操作和功能，主题必须完全符合当前脚本的更新。默认主题不适用
                                </p>
                            </div>
                        </div>
                    </div>
                    <table class="table">
                        <thead>
                            <th>
                                主题名称
                            </th>
                            <th>
                                主题作者
                            </th>
                            <th>
                                版本
                            </th>
                            <th>
                                来源
                            </th>
                            <th>
                                操作
                            </th>
                        </thead>
                        <tbody>
                            <?php foreach ($cl["themes"] as $theme): ?>
                                <tr>
                                    <td>
                                        <?php echo $theme["name"]; ?>
                                    </td>
                                    <td>
                                        <?php echo $theme["author"]; ?>
                                    </td>
                                    <td>
                                        <?php echo $theme["version"]; ?>
                                    </td>
                                    <td>
                                        <code>
                                            <?php echo cl_strf("themes/%s", $theme["src"]); ?>
                                        </code>
                                    </td>
                                    <td>
                                        <?php if ($theme["src"] == $cl["config"]["theme"]): ?>
                                            <span class="badge bg-red">
                                                当前主题
                                            </span>
                                        <?php else: ?>
                                            <button class="btn btn-primary btn-md" onclick="SMC_CPanel.PS.activate_theme('<?php echo $theme["src"] ?>', this);">
                                                激活
                                            </button>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/themes/scripts/app_master_script'); ?>